name: Android CI
env:
  # Module names for your project
  app_module: app
  # Project name
  project_name: SmsGateway
on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
      # Extract version from build.gradle.kts
      - name: Extract version information
        run: |
          # SmsGateway version
          APP_VERSION=$(grep -o 'versionName = "[^"]*"' ${{ env.app_module }}/build.gradle.kts | cut -d'"' -f2)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          
          # Use server version for the release tag (you can modify this as needed)
          echo "RELEASE_VERSION=$APP_VERSION" >> $GITHUB_ENV
      
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      # App Build
      - name: Build SmsGateway APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
          ./gradlew assembleRelease
      
      # Upload SmsGateway Debug APK as artifact
      - name: Upload SmsGateway APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.project_name }} - SmsGateway - Debug APK
          path: ${{ env.app_module }}/build/outputs/apk/debug/
      
      # Upload SmsGateway Release APK as artifact
      - name: Upload SmsGateway APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.project_name }} - SmsGateway - Release APK
          path: ${{ env.app_module }}/build/outputs/apk/release/
      
      # Rename APKs for easier identification
      - name: Rename APKs
        run: |
          mkdir -p release_files
          cp ${{ env.app_module }}/build/outputs/apk/debug/*.apk release_files/SmsGateway-App-${{ env.APP_VERSION }}-debug.apk
          cp ${{ env.app_module }}/build/outputs/apk/release/*.apk release_files/SmsGateway-App-${{ env.APP_VERSION }}-release.apk
          
      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          name: Release v${{ env.RELEASE_VERSION }}
          body: |
            SmsGateway Release v${{ env.RELEASE_VERSION }} (${{ env.date_today }})
            
            This release contains:
            - SmsGateway APK v${{ env.APP_VERSION }} (Debug & Release)
            
            Built automatically using GitHub Actions.
          draft: false
          prerelease: false
          files: |
            release_files/SmsGateway-App-${{ env.APP_VERSION }}-debug.apk
            release_files/SmsGateway-App-${{ env.APP_VERSION }}-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
